### ISSUE TITLE
Convert analysis to notebook

### ISSUE THREAD

**Issue by 0xjeremyfrank** [abhi3700/semantic-hashing-demo#3]
Currently the analysis isn't very straight forward to conduct. I'm not sure what I need to actually run to get to the final output. It is also not easily repeatable. I think two improvements should be made:

- [x] Improved documentation
- [x] Add python notebook to allow for data exploration and saving of results

**Comment by abhi3700** [comment]
Actually, the README currently covers all the steps to run the 4 scripts as used so far.

Still, I will convert all into a jupyter notebook.

**Comment by 0xjeremyfrank** [comment]
The below is not sufficient documentation. I don't think they are in the correct order and they don't actually explain what is done. Also, in my environment `huak run ...` always tells me that `...` does not exist. Is there a step missing in the documentation?

```
# pre-process input data to buckets
huak run preprocess

# detect similar text
huak run detect

# generate texts (source, variant)
huak run generate

# process generated texts (source, variant)
huak run post_generate
```

**Comment by abhi3700** [comment]
Actually, you needed to ensure [this](https://github.com/abhi3700/semantic-hashing-demo/blob/cbbc89af303fd09baced543100799aec0f40599a/README.md#L9-L29) first.
It would be helpful for me to diagnose the issue, if you could help me with the error following 🔝 .

The sequence is accordingly set in [README](https://github.com/abhi3700/semantic-hashing-demo/blob/main/README.md).

**Comment by 0xjeremyfrank** [comment]
I do not think the readme documentation is adequate. I should be able to clone the repo and know exactly what I need to do to run the analysis, including what each step does, which are optional, etc. I should be able to do this with somewhat limited context.

**Comment by abhi3700** [comment]
> I do not think the readme documentation is adequate. I should be able to clone the repo and know exactly what I need to do to run the analysis, including what each step does, which are optional, etc. I should be able to do this with somewhat limited context.

Added in commit: https://github.com/abhi3700/semantic-hashing-demo/pull/4/commits/6d2fd28932494e61ec056d1c7c92e924fea60545
